// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Author struct {
	ID   uuid.UUID      `db:"id" json:"id"`
	Name string         `db:"name" json:"name"`
	Bio  sql.NullString `db:"bio" json:"bio"`
}

type Credential struct {
	ID             uuid.UUID      `db:"id" json:"id"`
	Name           string         `db:"name" json:"name"`
	Description    sql.NullString `db:"description" json:"description"`
	CredentialType string         `db:"credential_type" json:"credentialType"`
	FolderID       uuid.UUID      `db:"folder_id" json:"folderId"`
	Domain         sql.NullString `db:"domain" json:"domain"`
	CreatedBy      uuid.NullUUID  `db:"created_by" json:"createdBy"`
	CreatedAt      time.Time      `db:"created_at" json:"createdAt"`
	UpdatedBy      uuid.NullUUID  `db:"updated_by" json:"updatedBy"`
	UpdatedAt      time.Time      `db:"updated_at" json:"updatedAt"`
}

type CredentialAccess struct {
	ID           uuid.UUID     `db:"id" json:"id"`
	CreatedAt    time.Time     `db:"created_at" json:"createdAt"`
	UpdatedAt    time.Time     `db:"updated_at" json:"updatedAt"`
	CredentialID uuid.UUID     `db:"credential_id" json:"credentialId"`
	UserID       uuid.UUID     `db:"user_id" json:"userId"`
	AccessType   string        `db:"access_type" json:"accessType"`
	GroupID      uuid.NullUUID `db:"group_id" json:"groupId"`
	FolderID     uuid.NullUUID `db:"folder_id" json:"folderId"`
}

type Field struct {
	ID           uuid.UUID     `db:"id" json:"id"`
	FieldName    string        `db:"field_name" json:"fieldName"`
	FieldValue   string        `db:"field_value" json:"fieldValue"`
	FieldType    string        `db:"field_type" json:"fieldType"`
	CredentialID uuid.UUID     `db:"credential_id" json:"credentialId"`
	UserID       uuid.UUID     `db:"user_id" json:"userId"`
	CreatedAt    time.Time     `db:"created_at" json:"createdAt"`
	CreatedBy    uuid.NullUUID `db:"created_by" json:"createdBy"`
	UpdatedAt    time.Time     `db:"updated_at" json:"updatedAt"`
	UpdatedBy    uuid.NullUUID `db:"updated_by" json:"updatedBy"`
}

type Folder struct {
	ID          uuid.UUID      `db:"id" json:"id"`
	CreatedAt   time.Time      `db:"created_at" json:"createdAt"`
	UpdatedAt   time.Time      `db:"updated_at" json:"updatedAt"`
	Name        string         `db:"name" json:"name"`
	Description sql.NullString `db:"description" json:"description"`
	CreatedBy   uuid.NullUUID  `db:"created_by" json:"createdBy"`
}

type FolderAccess struct {
	ID         uuid.UUID     `db:"id" json:"id"`
	CreatedAt  time.Time     `db:"created_at" json:"createdAt"`
	UpdatedAt  time.Time     `db:"updated_at" json:"updatedAt"`
	FolderID   uuid.UUID     `db:"folder_id" json:"folderId"`
	UserID     uuid.UUID     `db:"user_id" json:"userId"`
	AccessType string        `db:"access_type" json:"accessType"`
	GroupID    uuid.NullUUID `db:"group_id" json:"groupId"`
}

type GroupList struct {
	ID         uuid.UUID `db:"id" json:"id"`
	GroupingID uuid.UUID `db:"grouping_id" json:"groupingId"`
	UserID     uuid.UUID `db:"user_id" json:"userId"`
	AccessType string    `db:"access_type" json:"accessType"`
	CreatedAt  time.Time `db:"created_at" json:"createdAt"`
}

type Grouping struct {
	ID        uuid.UUID     `db:"id" json:"id"`
	CreatedAt time.Time     `db:"created_at" json:"createdAt"`
	UpdatedAt time.Time     `db:"updated_at" json:"updatedAt"`
	Name      string        `db:"name" json:"name"`
	CreatedBy uuid.NullUUID `db:"created_by" json:"createdBy"`
}

type SessionTable struct {
	ID        uuid.UUID      `db:"id" json:"id"`
	UserID    uuid.UUID      `db:"user_id" json:"userId"`
	PublicKey string         `db:"public_key" json:"publicKey"`
	Challenge string         `db:"challenge" json:"challenge"`
	DeviceID  sql.NullString `db:"device_id" json:"deviceId"`
	SessionID sql.NullString `db:"session_id" json:"sessionId"`
	CreatedAt sql.NullTime   `db:"created_at" json:"createdAt"`
	UpdatedAt sql.NullTime   `db:"updated_at" json:"updatedAt"`
}

type User struct {
	ID                    uuid.UUID      `db:"id" json:"id"`
	CreatedAt             time.Time      `db:"created_at" json:"createdAt"`
	UpdatedAt             time.Time      `db:"updated_at" json:"updatedAt"`
	Username              string         `db:"username" json:"username"`
	Name                  string         `db:"name" json:"name"`
	EncryptionKey         sql.NullString `db:"encryption_key" json:"encryptionKey"`
	DeviceKey             sql.NullString `db:"device_key" json:"deviceKey"`
	TempPassword          string         `db:"temp_password" json:"tempPassword"`
	RegistrationChallenge sql.NullString `db:"registration_challenge" json:"registrationChallenge"`
	SignedUp              bool           `db:"signed_up" json:"signedUp"`
	Type                  string         `db:"type" json:"type"`
	Status                string         `db:"status" json:"status"`
}
