// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAuthor(ctx context.Context, arg CreateAuthorParams) (Author, error)
	CreateFolder(ctx context.Context, arg CreateFolderParams) (CreateFolderRow, error)
	DeleteAuthor(ctx context.Context, id uuid.UUID) error
	GetAuthor(ctx context.Context, id uuid.UUID) (Author, error)
	GetFoldersForUser(ctx context.Context, createdBy uuid.NullUUID) ([]Folder, error)
	ListAuthors(ctx context.Context) ([]Author, error)
	UpdateAuthor(ctx context.Context, arg UpdateAuthorParams) error
}

var _ Querier = (*Queries)(nil)
